export { default as Home } from './Dashboard/Home'
export { default as MainLayout } from './Dashboard/MainLayout'
export { default as Profile } from './Dashboard/Profile'
export { default as Search } from './Dashboard/Search'
export { default as CourseListing } from './Course/CourseListing'
export { default as CourseDetail } from './Course/CourseDetail'
export { default as CourseFiles} from './Course/CourseTabs/CourseFiles'
export { default as CourseChapters } from './Course/CourseTabs/CourseChapters'
export { default as CourseDiscussion } from './Course/CourseTabs/CourseDiscussion'